apiVersion: v1
kind: Pod
metadata:
  name: microservice-libreria-pod
  labels:
    app: microservice-libreria
    type: microservice
spec:
  containers:
  - name: microservice-libreria-app
    image: lcano23/serviciosapilibreria:latest
    ports:
        - containerPort: 80
    env:
        - name: MongoDb__ConnectionString
          value: mongodb://lcano:lcano23@mongo-service:27017